'use client'

import { useActionState, useState, useEffect } from 'react'
import { loginAction } from '@/app/actions/auth'

// Brand assets
const LOGO_COLOR = 'https://isimova.com/assets/img/Isimova-Color-Horizontal.png'
const WA_LINK = 'https://wa.me/51913279269?text=Hola%20Isimova,%20deseo%20m%C3%A1s%20informaci%C3%B3n%20'

const SLIDES = [
  {
    tagline: 'Biblioteca de Cursos',
    title: 'Aprende. Certifícate. Lidera.',
    desc: 'Accede a más de 1200 horas académicas con metodología práctica y casos reales aplicables desde el primer módulo.',
    image: '/img/slide-1.png',
  },
  {
    tagline: 'Respaldo Universitario',
    title: 'Certificaciones con Validez Nacional',
    desc: 'Diplomas avalados por la Universidad Nacional de Trujillo y la Univ. San Luis Gonzaga. Válidos para MINSA y EsSalud.',
    image: '/img/slide-2.png',
  },
  {
    tagline: 'Acompañamiento Continuo',
    title: 'No Estudias Solo.',
    desc: 'Un equipo de docentes con experiencia real en el sector te guía durante todo el diplomado — no solo teoría.',
    image: '/img/slide-3.png',
  },
]

// ─── Mobile Onboarding Carousel (App style) ──────────────────────────────────
function MobileOnboardingSlideshow() {
  const [active, setActive] = useState(0)

  useEffect(() => {
    const id = setInterval(() => {
      setActive(prev => (prev + 1) % SLIDES.length)
    }, 4500)
    return () => clearInterval(id)
  }, [])

  return (
    <div className="flex flex-col w-full overflow-x-hidden">
      {/* Sliding Images + Text Container */}
      <div className="relative overflow-visible w-full">
        <div
          className="flex transition-transform duration-500 ease-in-out w-full"
          style={{ transform: `translateX(-${active * 100}%)` }}
        >
          {SLIDES.map((slide, i) => (
            <div key={i} className="w-full shrink-0 flex flex-col items-center px-6">
              {/* Illustration Placeholder (Generated by AI) */}
              <div className="w-full max-w-[280px] aspect-4/3 rounded-3xl mb-6 flex items-center justify-center">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={slide.image}
                  alt={slide.title}
                  className="w-full h-full object-contain"
                />
              </div>

              {/* Fixed Height Text Container to prevent jumping */}
              <div className="h-[140px] w-full text-center flex flex-col items-center justify-start">
                <p className="text-primary text-[10px] font-bold tracking-[0.2em] uppercase mb-2 line-clamp-1">
                  {slide.tagline}
                </p>
                <h2 className="text-slate-900 text-[22px] font-black tracking-tight leading-tight mb-3">
                  {slide.title}
                </h2>
                <p className="text-slate-500 text-[13px] leading-relaxed max-w-[320px]">
                  {slide.desc}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Dot indicators (Standardized to center) */}
      <div className="flex justify-center gap-2 mt-2">
        {SLIDES.map((_, i) => (
          <button
            key={i}
            onClick={() => setActive(i)}
            aria-label={`Slide ${i + 1}`}
            className="rounded-full transition-all duration-300"
            style={{
              height: '4px',
              width: i === active ? '24px' : '4px',
              background: i === active ? 'var(--color-primary, #f97316)' : 'rgba(0,0,0,0.1)',
            }}
          />
        ))}
      </div>
    </div>
  )
}

// ─── Slideshow with glassmorphism card ───────────────────────────────────────
function BrandSlideshow({ dark = false }: { dark?: boolean }) {
  const [active, setActive] = useState(0)
  const [visible, setVisible] = useState(true)

  useEffect(() => {
    const id = setInterval(() => {
      setVisible(false)
      setTimeout(() => {
        setActive(prev => (prev + 1) % SLIDES.length)
        setVisible(true)
      }, 300)
    }, 5000)
    return () => clearInterval(id)
  }, [])

  const slide = SLIDES[active]
  const titleColor = dark ? 'text-white' : 'text-slate-900'
  const taglineColor = 'text-primary'
  const descColor = dark ? 'text-white/70' : 'text-slate-600'
  const borderAccent = 'border-primary/40'

  return (
    <div className="flex flex-col gap-4">
      <div
        style={{
          opacity: visible ? 1 : 0,
          transform: visible ? 'translateY(0)' : 'translateY(8px)',
          transition: 'opacity 300ms ease, transform 300ms ease',
        }}
      >
        <p className={`${taglineColor} text-xs font-bold tracking-[0.2em] uppercase mb-2`}>
          {slide.tagline}
        </p>
        <h2 className={`${titleColor} text-2xl lg:text-3xl font-black tracking-tight leading-snug mb-3`}>
          {slide.title}
        </h2>
        <p className={`${descColor} text-sm leading-relaxed border-l-2 ${borderAccent} pl-3`}>
          {slide.desc}
        </p>
      </div>

      {/* Dot indicators */}
      <div className="flex gap-2 mt-1">
        {SLIDES.map((_, i) => (
          <button
            key={i}
            onClick={() => { setActive(i); setVisible(true) }}
            aria-label={`Slide ${i + 1}`}
            className="rounded-full transition-all duration-300"
            style={{
              height: '3px',
              width: i === active ? '24px' : '6px',
              background: i === active ? 'var(--color-primary, #f97316)' : 'rgba(0,0,0,0.15)',
            }}
          />
        ))}
      </div>
    </div>
  )
}

// ─── Shared form fields ───────────────────────────────────────────────────────
function LoginForm({
  action,
  pending,
  stateError,
  dniId,
  passwordId,
}: {
  action: (payload: FormData) => void
  pending: boolean
  stateError?: string | null
  dniId: string
  passwordId: string
}) {
  return (
    <form action={action} className="space-y-5">
      <div>
        <label
          htmlFor={dniId}
          className="block text-xs font-bold uppercase tracking-widest text-slate-500 mb-2"
        >
          DNI
        </label>
        <input
          id={dniId}
          name="dni"
          required
          type="text"
          inputMode="numeric"
          pattern="\d{8}"
          maxLength={8}
          minLength={8}
          placeholder="12345678"
          className="w-full rounded-xl bg-white border border-slate-200 py-3.5 px-4 text-slate-900 placeholder:text-slate-300 focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all text-sm font-medium shadow-sm"
        />
      </div>

      <div>
        <label
          htmlFor={passwordId}
          className="block text-xs font-bold uppercase tracking-widest text-slate-500 mb-2"
        >
          Contraseña
        </label>
        <input
          id={passwordId}
          name="password"
          required
          type="password"
          placeholder="••••••••"
          className="w-full rounded-xl bg-white border border-slate-200 py-3.5 px-4 text-slate-900 placeholder:text-slate-300 focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none transition-all text-sm font-medium shadow-sm"
        />
      </div>

      {stateError && (
        <div className="p-3 bg-red-50 border border-red-200 rounded-xl">
          <p className="text-xs font-bold text-red-600 uppercase tracking-wide">{stateError}</p>
        </div>
      )}

      <button
        disabled={pending}
        type="submit"
        className="w-full h-14 bg-primary hover:bg-primary-variant text-white font-black uppercase tracking-widest rounded-xl shadow-lg shadow-primary/25 hover:shadow-primary/35 transition-all active:scale-[0.98] disabled:opacity-80 disabled:cursor-not-allowed mt-1 flex items-center justify-center gap-3 relative overflow-hidden"
      >
        {pending ? (
          <div className="flex gap-1.5 items-center justify-center">
            <span className="w-2.5 h-2.5 bg-white rounded-full animate-bounce-dots [animation-delay:-0.32s]"></span>
            <span className="w-2.5 h-2.5 bg-white rounded-full animate-bounce-dots [animation-delay:-0.16s]"></span>
            <span className="w-2.5 h-2.5 bg-white rounded-full animate-bounce-dots"></span>
          </div>
        ) : (
          <>
            <span>Iniciar Sesión</span>
            <svg
              className="w-5 h-5 -mr-1 opacity-90"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              strokeWidth={2.5}
            >
              <path strokeLinecap="round" strokeLinejoin="round" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
            </svg>
          </>
        )}
      </button>
    </form>
  )
}

// ─── Interactive Background ───────────────────────────────────────────────────
function InteractiveSpotlight() {
  const [position, setPosition] = useState({ x: 0, y: 0 })
  const [isHovered, setIsHovered] = useState(false)

  const handleMouseMove = (e: React.MouseEvent) => {
    const rect = e.currentTarget.getBoundingClientRect()
    setPosition({
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    })
  }

  return (
    <div 
      className="absolute inset-0 bg-[#0a1128] overflow-hidden"
      onMouseMove={handleMouseMove}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {/* Dot Pattern Overlay */}
      <div 
        className="absolute inset-0 opacity-20"
        style={{
          backgroundImage: 'radial-gradient(circle at center, #ffffff 1px, transparent 1px)',
          backgroundSize: '24px 24px'
        }}
      />
      
      {/* Orange Spotlight (Vibrant ISIMOVA Orange) */}
      <div
        className="pointer-events-none absolute inset-0 transition-opacity duration-500 ease-in-out"
        style={{
          opacity: isHovered ? 1 : 0,
          background: `radial-gradient(circle 700px at ${position.x}px ${position.y}px, rgba(249, 115, 22, 0.15), transparent 100%)`
        }}
      />
      <div
        className="pointer-events-none absolute inset-0 transition-opacity duration-300 ease-in-out"
        style={{
          opacity: isHovered ? 1 : 0,
          background: `radial-gradient(circle 350px at ${position.x}px ${position.y}px, rgba(249, 115, 22, 0.22), transparent 100%)`
        }}
      />
      
      {/* Subtle ambient glow to avoid pitch black when not hovered */}
      <div className="absolute inset-0 bg-linear-to-tr from-[#0a1128] via-transparent to-primary/5 pointer-events-none" />
    </div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function LoginPage() {
  const [state, action, pending] = useActionState(loginAction, null)
  const [sheetOpen, setSheetOpen] = useState(false)

  useEffect(() => {
    document.body.style.overflow = sheetOpen ? 'hidden' : ''
    return () => { document.body.style.overflow = '' }
  }, [sheetOpen])

  return (
    <div className="min-h-dvh font-sans antialiased">

      {/* ══════════════════════════════════════
          DESKTOP LAYOUT (md+)
          Interactive Dynamic Background | Form
      ══════════════════════════════════════ */}
      <div className="hidden md:flex min-h-dvh bg-slate-50">

        {/* ── Left: Brand panel ──────────────── */}
        <div className="w-1/2 relative flex flex-col overflow-hidden">

          {/* Interactive Mouse Spotlight Background */}
          <InteractiveSpotlight />

          {/* ── Glassmorphism slideshow card ── */}
          {/* We make the glassmorphism dark to contrast perfectly with the deep blue background */}
          <div className="relative z-10 flex-1 flex items-end pb-16 px-10 pointer-events-none">
            <div
              className="w-full rounded-2xl p-6 pointer-events-auto"
              style={{
                background: 'rgba(15, 23, 42, 0.45)', // slate-900 modified
                backdropFilter: 'blur(24px)',
                WebkitBackdropFilter: 'blur(24px)',
                border: '1px solid rgba(255,255,255,0.1)',
                boxShadow: '0 8px 32px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.05)',
              }}
            >
              <BrandSlideshow dark={true} />
            </div>
          </div>
        </div>

        {/* ── Right: Form panel ──────────────── */}
        <div className="w-1/2 flex flex-col justify-center items-center bg-white relative px-12 lg:px-16 py-12">

          {/* Subtle brand stripe at top */}
          <div className="absolute top-0 left-0 right-0 h-0.5 bg-linear-to-r from-isimova-blue via-primary to-isimova-blue opacity-60" />

          {/* Glassmorphism form card */}
          <div
            className="w-full max-w-sm rounded-3xl p-8"
            style={{
              background: 'rgba(248,250,252,0.85)',
              backdropFilter: 'blur(12px)',
              WebkitBackdropFilter: 'blur(12px)',
              border: '1px solid rgba(226,232,240,0.8)',
              boxShadow: '0 4px 24px rgba(0,0,0,0.06), inset 0 1px 0 rgba(255,255,255,1)',
            }}
          >
            {/* Logo inside card */}
            <a href="https://isimova.com" className="inline-block mb-7" tabIndex={-1}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={LOGO_COLOR} alt="ISIMOVA" className="h-9 w-auto object-contain" />
            </a>

            <div className="mb-6">
              <h1 className="text-2xl font-black tracking-tight text-slate-900 leading-tight mb-1">
                Ingresa a tu cuenta
              </h1>
              <p className="text-slate-500 text-sm">
                Continúa tu camino hacia la certificación.
              </p>
            </div>

            <LoginForm
              action={action}
              pending={pending}
              stateError={state?.error}
              dniId="dni-desktop"
              passwordId="password-desktop"
            />
          </div>
        </div>
      </div>

      {/* ══════════════════════════════════════
          MOBILE LAYOUT (< md) - APP ONBOARDING PURE
      ══════════════════════════════════════ */}
      <div className="md:hidden h-[100dvh] flex flex-col relative overflow-hidden bg-white justify-between">
        
        {/* ── Top Bar: Back Arrow & Centered Logo ── */}
        <div className="relative z-10 flex items-center justify-between px-6 pt-10 pb-4 shrink-0">
          <a href="https://isimova.com" className="p-2 -ml-2 text-slate-400 hover:text-slate-900 transition-colors">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
          </a>
          <div className="flex-1 flex justify-center">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={LOGO_COLOR} alt="ISIMOVA" className="h-10 w-auto object-contain" />
          </div>
          <div className="w-10" /> {/* Spacer to force center alignment perfectly */}
        </div>

        {/* ── Onboarding App Carousel Area ── */}
        <div className="flex-1 flex flex-col justify-center w-full">
          <MobileOnboardingSlideshow />
        </div>

        {/* ── CTA button — Pulled UP to avoid WhatsApp overlap (pb-24) ── */}
        <div className="relative z-10 px-6 pt-6 pb-24 shrink-0 mx-auto w-full max-w-[360px]">
          <div className="relative group">
            <div className="absolute -inset-1 bg-primary/20 rounded-xl blur-md opacity-70 group-hover:opacity-100 transition duration-500 animate-[pulse_3s_ease-in-out_infinite]"></div>
            <button
              id="open-login-btn"
              onClick={() => setSheetOpen(true)}
              className="relative w-full h-14 bg-linear-to-r from-primary to-[#ea580c] hover:brightness-110 text-white font-black uppercase tracking-widest rounded-xl shadow-lg transition-transform active:scale-[0.98] flex items-center justify-between px-6"
            >
              <span>Ingresar a mi cuenta</span>
              <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      {/* ══════════════════════════════════════
          BOTTOM SHEET (Mobile only)
      ══════════════════════════════════════ */}

      {/* Backdrop */}
      <div
        onClick={() => setSheetOpen(false)}
        className="md:hidden fixed inset-0 z-40 backdrop-blur-sm transition-opacity duration-300"
        style={{
          background: 'rgba(0,0,0,0.45)',
          opacity: sheetOpen ? 1 : 0,
          pointerEvents: sheetOpen ? 'auto' : 'none',
        }}
      />

      {/* Sheet */}
      <div
        className="md:hidden fixed bottom-0 left-0 right-0 z-50 bg-white rounded-t-3xl"
        style={{
          transform: sheetOpen ? 'translateY(0)' : 'translateY(100%)',
          transition: 'transform 450ms cubic-bezier(0.32, 0.72, 0, 1)',
          maxHeight: '90dvh',
          overflowY: 'auto',
          boxShadow: '0 -20px 60px rgba(0,0,0,0.18)',
        }}
      >
        {/* Handle pill */}
        <div className="flex justify-center pt-4 pb-2">
          <div className="w-10 h-1.5 bg-slate-200 rounded-full" />
        </div>

        <div className="px-7 pb-10 pt-3">
          {/* Sheet header */}
          <div className="mb-6">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={LOGO_COLOR} alt="ISIMOVA" className="h-8 w-auto object-contain mb-5" />
            <h2 className="text-2xl font-black tracking-tight text-slate-900 mb-1">
              Ingresa a tu cuenta
            </h2>
            <p className="text-slate-500 text-sm">Continúa tu camino hacia la certificación.</p>
          </div>

          <LoginForm
            action={action}
            pending={pending}
            stateError={state?.error}
            dniId="dni-mobile"
            passwordId="password-mobile"
          />

          <button
            onClick={() => setSheetOpen(false)}
            className="w-full mt-4 py-3 text-slate-400 text-sm font-medium hover:text-slate-600 transition-colors"
          >
            Cancelar
          </button>
        </div>
      </div>

      {/* ══════════════════════════════════════
          WhatsApp FAB
      ══════════════════════════════════════ */}
      <a
        href={WA_LINK}
        target="_blank"
        rel="noopener noreferrer"
        id="wa-fab"
        aria-label="Contactar por WhatsApp"
        className="fixed bottom-6 right-6 z-45 w-14 h-14 bg-[#25D366] hover:bg-[#20bd5a] text-white rounded-full shadow-xl shadow-green-900/20 transition-all hover:scale-110 active:scale-95 flex items-center justify-center"
        style={{ display: sheetOpen ? 'none' : 'flex' }}
      >
        <svg viewBox="0 0 24 24" className="w-7 h-7 fill-current">
          <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" />
        </svg>
      </a>
    </div>
  )
}
